### ISSUE TITLE
无法自动找到番剧呢

### ISSUE THREAD

**Issue by luojianxhlxt** [Trim21/bgm-tv-auto-tracker#19]
问题页面: [null](https://www.iqiyi.com/v_19rr5c08b8.html)
Bangumi ID: a_19rrh70a9p
episode: 0
bgm page: 
Subject: https://bgm.tv/subject/null
episode: https://bgm.tv/ep/null

http://bangumi.tv/subject/240562
应该是这个subject
还是我理解有问题，需要自己手动找啊。。。

**Comment by trim21** [comment]
你理解的没错...
换季的时候稍微有一些延迟....
