### ISSUE TITLE
没有同步

### ISSUE THREAD

**Issue by SoraHaruka** [Trim21/bgm-tv-auto-tracker#21]
问题页面: [关于我转生变成史莱姆这档事](https://www.bilibili.com/bangumi/play/ep250470)
Bangumi ID: 25739
episode: 11
bgm page: 
Subject: https://bgm.tv/subject/239816
episode: https://bgm.tv/ep/831198

**Comment by trim21** [comment]
无法同步是指什么, 没法在bgm上自动标记吗
