### ISSUE TITLE
笨拙之极的上野 对应关系错误：对应到了漫画

### ISSUE THREAD

**Issue by no1xsyzy** [Trim21/bgm-tv-auto-tracker#24]
问题页面: [笨拙之极的上野](https://www.bilibili.com/bangumi/play/ep259596)
Bangumi ID: 26298
episode: 1
bgm page: 
Subject: https://bgm.tv/subject/133637
episode: https://bgm.tv/ep/null

对应页面本应为 https://bgm.tv/subject/247417
但却对应到了漫画

**Comment by trim21** [comment]
谢谢反馈
